language: node_js

node_js:
  - "0.10"

env:
  global:
    - SAUCE_USERNAME="osbdemo"

addons:
  jwt:
     saucelabs:
        secure: "txjn9yM8sO6f90LPNhc/nmAPOFZNBT7nt8f5OZh1MAfltcPqupwEtQr7hHhSdnNWb+4SYHrrhRKy0YA4GdsC356KcIhJtTfKnckEasmr30U2Z6Kt5Wx71FktFiLR2D4aezQx0sgQOJ1kX/Myokpk8hAgP1Ho/ifmnrsSbjBX10M="

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - ./travis.sh before

after_success:
  - ./travis.sh merge

after_failure:
  - ./travis.sh revert

notifications:
  email:
    on_success: never
